### ISSUE TITLE
Option to pass MYSQL_UID and MYSQL_GID as parameters to the Dockerfile

### ISSUE THREAD

**Issue by telkamp** [jbergstroem/mariadb-alpine#121]
I guess that the user:group `mysql:mysql` is created during the installation of mariadb. uid:gid was `1000:1000`, what
was mapped to a test user on the host machine in my case. Therefore, the files in the volume folder on my machine under `/var/lib/docker/volumes/../..` were owned by this test user.

To solve this, I have defined the uid:gid to be used by `mysql:mysql` as arguments MYSQL_UID and MYSQL_GID in the `Dockerfile`:
```
@@ -1,6 +1,8 @@
 FROM alpine:3.15
 
 # https://github.com/opencontainers/image-spec/blob/master/annotations.md
+ARG MYSQL_UID=1000
+ARG MYSQL_GID=1000
 ARG BUILD_DATE
 ARG VCS_REF
 
@@ -17,6 +19,7 @@ LABEL org.opencontainers.image.created=$BUILD_DATE \
 SHELL ["/bin/ash", "-euo", "pipefail", "-c"]
 
 RUN \
+  addgroup --system --gid ${MYSQL_GID} mysql && adduser --system --ingroup mysql --uid ${MYSQL_UID} mysql && \
   apk add --no-cache mariadb=10.6.4-r2 && \
   TO_KEEP=$(echo " \
     etc/ssl/certs/ca-certificates.crt$ \
```
These arguments may be passed by the `docker-compose.yml`:
```
    [...]
    build:
      context: mariadb-alpine
      dockerfile: ./Dockerfile
      args:
        - MYSQL_UID=${MYSQL_UID:-1000}
        - MYSQL_GID=${MYSQL_GID:-1000}
    [...]
```
The disadvantage of this solution is that the container has to be built on the host machine, so it can not be pulled from Docker Hub.
Setting a different `user` for the container pulled from Docker Hub did not worked for me, because this user had no privileges
to copy files to `/etc/my.cnf.d/` (see `run.sh:11`)
Maybe there are better solutions?
