### ISSUE TITLE
Use mysql client for healthchecks

### ISSUE THREAD

**Issue by williamdes** [jbergstroem/mariadb-alpine#212]
```yaml
    db:
        image: jbergstroem/mariadb-alpine:10.6.12
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
            interval: 30s
            timeout: 1s
            retries: 3
            start_period: 8s
        environment:
            MYSQL_ROOT_PASSWORD: public
            MYSQL_DATABASE: public
            MYSQL_USER: public
            MYSQL_PASSWORD: public
```
