### ISSUE TITLE
Can't connect to mysql server because it starts with skip-networking=TRUE

### ISSUE THREAD

**Issue by jones1008** [jbergstroem/mariadb-alpine#62]
I have the following `docker-compose.yml` setup:
```yaml
services:
  db:
    image: jbergstroem/mariadb-alpine:10.4.15
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
```
At intial startup it loads the file `./db/test.sql` into the database `test`.
After the container starts, I try to connect to it with a local `mysql` client installation:
```
>mysql -uroot -proot
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 2 "No such file or directory"
```
and on the Docker output I get:
```
Version: '10.4.15-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
```
Note the port is set to `0` instead of `3306`. A [quick search](https://stackoverflow.com/a/9979483/7987318) states that `--skip-networking` might be enabled.
And in fact [the `sh/run.sh` script](https://github.com/jbergstroem/mariadb-alpine/blob/cbc8ece2029a1101048c9fcb2653450d64f65a04/sh/run.sh#L67) starts the temporary mysql daemon with the `--skip-networking` flag to import my `test.sql`.

My guess is that `mysqld` somehow saves the variable `skip-networking` internally and keeps it to `TRUE` when [executing `mysqld` in the last line of `run.sh`](https://github.com/jbergstroem/mariadb-alpine/blob/cbc8ece2029a1101048c9fcb2653450d64f65a04/sh/run.sh#L102)

A solution might be to explicitly set `--skip-networking=FALSE` in the [last line of `run.sh`](https://github.com/jbergstroem/mariadb-alpine/blob/cbc8ece2029a1101048c9fcb2653450d64f65a04/sh/run.sh#L102). Might be filing a PR soon.

Also note that somehow this is not an issue in the [latest mariadb version 10.4.17](https://hub.docker.com/layers/jbergstroem/mariadb-alpine/10.4.17/images/sha256-10b0b0779dcd5bad40432522e6da4e51cd5d8bb811410efdfb1537c3880bac68)...
So changing the `docker-compose.yml` to the following fixes the issue:
```yaml
services:
  db:
    image: jbergstroem/mariadb-alpine:10.4.17
    # ...
```

**Comment by jbergstroem** [comment]
Thanks for filing a bug report! Will investigate and try to reproduce.

**Comment by jones1008** [comment]
added a fix in PR #57

**Comment by jbergstroem** [comment]
I haven't been able to reproduce this. Is it happening 100% of the time for you?

**Comment by jones1008** [comment]
I just reproduced this on **another** Windows machine, when the container imports the `./db/test.sql`, so I guess it is happening 100% of the time:
```
init: installing mysql client
init: updating system tables
init: adding /docker-entrypoint-initdb.d/test.sql
init: removing mysql client
[...]
Version: '10.4.15-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
```
Please note, that I am using the image version `10.4.15` in my `docker-compose.yml` and not the latest version `10.4.17`.
Also: It didn't matter if I used the WSL2 based docker engine on Windows or the Hyper-V version, same problem for both...

**Comment by jbergstroem** [comment]
Ok, thanks for verifying. Since I aim to maintain latest branches of 10.4.x, 10.5.x (and possibly 10.3, 10.2); I'm unsure if I should merge a patch for a bug that's fixed upstream. What do you think?

**Comment by jones1008** [comment]
Well, if you want to support multiple branches of mariadb I think you want to fix this...
And since the [default value](https://mariadb.com/docs/reference/mdb/system-variables/skip_networking/#parameters) of `--skip-networking` is `OFF` anyway and I am only explicitly calling mysqld with this flag set to `false` [in my PR](https://github.com/jbergstroem/mariadb-alpine/pull/57/files#diff-160f986b9fb78f6ee58f9c1c45edc104ee88ba64cad37eb47af50ba9144a99aaR110), I don't see a reason not to merge this.

**Comment by Dashman99** [comment]
I noticed that my docker-compose file and @jones1008 both were using the docker-entrypoint-initdb.d option so I just tested with commenting this out and mysqld runs on port 3306.

docker-compose output
```
db_1       | 2022-05-09 14:55:37 0 [Note] mysqld: ready for connections.
db_1       | Version: '10.5.15-MariaDB-1:10.5.15+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

docker-compose file 
```
 db:
    image: mariadb:10.5
    restart: always
    env_file:
      - ./db.env
#    volumes: 
#      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3309:3306
   ```

Here is the process list from the db container
```
root@c8df207a315a:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
mysql        1  0.0  2.0 1345568 84476 ?       Ssl  14:55   0:00 mysqld
root       157  1.5  0.0   4244  3516 pts/0    Ss   15:03   0:00 bash
root       165  0.0  0.0   5896  2872 pts/0    R+   15:03   0:00 ps aux
```
